### ISSUE TITLE
Sidebar - Story featured date

### ISSUE THREAD

**Issue by stitzelj** [ficlatte/main#14]
I'd like to add back into the sidebar the date a story is featured, similar to what we had back on Ficly. To make the tracking easier, since some stories end up featuring more than once, we could display either the first feature date or the latest feature date. Does the current table structure track feature dates and maintain that information once a story is no longer featured?

**Comment by ethel-t-frog** [comment]
I was going to confidently assert that the ftime field stores the date and time that a story was first featured.  It seems, however, that the latest ftime field is 5th May 2015, so that might suggest to me that this field stopped being populated when I migrated from Perl to Python/Django.

Oopsie.  That was remiss of me.  Sorry about that.

The code that does the featuring is in castle/management/commands/ficlatte_nightly.py, which should now be fixed.  It seems that the sidebar code doesn't do anything with ftime either.

**Comment by stitzelj** [comment]
#15 Pull request for this feature. I'll probably change the layout somewhat once I get around to giving the site a fresh coat of paint, but for now it's at least present.

**Comment by stitzelj** [comment]
Resolved with #15.
