### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by stitzelj** [ficlatte/main#23]
> **ethel-t-frog an hour ago Member**
I am happy with the migration code being in source control, if only because that is how I operated when I was doing this by myself.
>
>Having said that, I can also see the argument that there is no need to check in files that are generated automatically by Django in response to changes in models.py.
>
>Maybe we should have this discussion elsewhere (maybe raise a separate issue), and come to a decision one way or another.

This is actually a fair point, now that I think about it. There's no reason a contributor can't run the `makemigrations/migrate` commands themselves after updating their forks, so I can see and even approve of HSAR's recommendation to add the migrations directory to `.gitignore`.

**Comment by HSAR** [comment]
Can we not at some point change the master database tables listing and do away with all migrations altogether?

**Comment by HSAR** [comment]
Once the format is settled, and no more changes are being made.

**Comment by ethel-t-frog** [comment]
Migrations are necessary during development to keep the database in line with models.py.  That said, there is no possible benefit to people coming at the project now to have to subject their database engine to my every historical whim.  Just because the Ficlatté server's database arrived at its current schema by one route doesn't mean that everyone else's has to.  Coming at it with a fresh install, there is no reason not to go straight for the latest.  It saves time, and will probably end up with a more efficient final DB on-disk structure as well.

Anyone care to delete all the migrations and submit a PR?

**Comment by stitzelj** [comment]
I can take care of it with my next commit.

**Comment by stitzelj** [comment]
One of my commits in the current PR #31 drops the migrations directory from the source code, and it's really minimal trouble to re-run the `makemigrations/migrate` commands whenever the models are updated. If everyone's ok with that, we can probably close this issue and make that our working process moving forward.

**Comment by ethel-t-frog** [comment]
Sounds good to me
